---
title: "Cleaning Montgomery County BOE spending data"
output: html_document
date: "2023-02-08"
---
BOE spending update is at the bottom of the document.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#loading libraries
library(tidyverse)
library(refinr)
library(janitor)
library(dplyr)
library(stringr)
library(tidyr)
```
```{r}
#reading in the csv file for all MD counties from MD open data portal
boe_spending <- read_csv("~/Documents/GitHub/news_apps_spring_2022/boe_spending.csv") %>% 
  clean_names()

#filtering for Montgomery County Public Schools expenditures only
#omitting columns with no data for Montgomery County
montgomery_spending <- boe_spending %>% 
  filter(agency_name == "Montgomery County Public Schools") %>% 
  select(-purpose_of_payment_baltimore_county_only, -mbe)

```
```{r}
#reading in FY2022 Montgomery County Public Schools data
montgomery_fy2022 <- read_csv("~/Documents/GitHub/news_apps_spring_2022/montgomery_fy2022.csv") %>% 
  clean_names

#standardizing column names
montgomery_fy2022 <- montgomery_fy2022 %>% 
  rename(payee_name = vendor_supplier) %>% 
  rename(amount = amount_paid)

#adding column indicating the fiscal year
montgomery_fy2022["fiscal_year"] = "2022"
```
```{r}
#reading in FY2018 Montgomery County Public Schools data
montgomery_fy2018 <- read_csv("~/Documents/GitHub/news_apps_spring_2022/montgomery_fy2018.csv") %>% 
  clean_names

#standardizing column names
montgomery_fy2018 <- montgomery_fy2018 %>% 
  rename(payee_name = vendor_supplier) %>% 
  rename(amount = amount_paid)

#adding column indicating the fiscal year
montgomery_fy2018["fiscal_year"] = "2018"
```

```{r}
#changing fiscal_year to character so that I can combine the data for 2018, 2022 and the other years
montgomery_spending <- montgomery_spending %>% 
  mutate(fiscal_year = as.character(fiscal_year))

#combining into one dataframe
combined_montgomery_spending <- bind_rows(montgomery_spending, montgomery_fy2018, montgomery_fy2022)
```

```{r}
#creating a csv to load into OpenRefine
write_csv(combined_montgomery_spending, "~/Documents/GitHub/news_apps_spring_2022/combined_montgomery_spending.csv")

#changed columns not containing only numbers to all caps
combined_montgomery_spending <- combined_montgomery_spending %>% 
  mutate(payee_name = str_to_upper(payee_name),
         agency_name = str_to_upper(agency_name))

#Then I loaded the csv in OpenRefine and standardized the payee names as well as I could.
```

```{r}
#reading in new cleaned dataframe from OpenRefine
montgomery_spending_cleaned <- read_csv("~/Documents/GitHub/news_apps_spring_2022/montgomery_spending_cleaned.csv")

#I decided to shorten "SAINT" to "ST". This only applied in one case.
montgomery_spending_cleaned %>% 
  filter(str_detect(payee_cleaned, "SAINT"))

montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(payee_cleaned = case_when(
    str_detect(payee_cleaned, "SAINT") ~ "ST COLETTA OF GREATER WASHINGTON INC",
    TRUE ~ payee_cleaned))

# I noticed  in OpenRefine that names of school boards and school systems weren't standardized across counties. I decided to keep school systems and school boards separate in case Baltimore County Public Schools is different from the BOE.
montgomery_spending_cleaned %>% 
  filter(str_detect(payee_cleaned, "BOARD OF ED"))

montgomery_spending_cleaned %>% 
  filter(str_detect(payee_cleaned, "SCHOOL"))

montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(payee_cleaned = case_when(
    str_detect(payee_cleaned, "BOARD OF EDUCATION OF BALTIMORE COUNTY") ~ "BALTIMORE COUNTY BOARD OF EDUCATION",
    str_detect(payee_cleaned, "BOARD OF EDUCATION PRINCE GEORGE'S") ~ "PRINCE GEORGE'S COUNTY BOARD OF EDUCATION",
    str_detect(payee_cleaned, "ANNE ARUNDEL CO PUBLIC SCHOOL") ~ "ANNE ARUNDEL COUNTY PUBLIC SCHOOLS",
    str_detect(payee_cleaned, "THE HOWARD COUNTY PUBLIC SCHOOL SYSTEM") ~ "HOWARD COUNTY PUBLIC SCHOOLS",
    TRUE ~ payee_cleaned))
```

```{r}
#I decided to take the approach that less punctuation is for the best. So I got rid of periods.
montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(payee_cleaned = str_replace_all(payee_cleaned, "\\.", ""))

#I also decided to get rid of commas.
montgomery_spending_cleaned %>% 
  filter(str_detect(payee_cleaned, ", "))

#Here I realized that using case_when this way replaces the entire string in the payee_cleaned column with just "INC" or "PC". But then I took a different approach with commas anyway - getting rid of all commas and then making a column indicating whether or not each payee was an individual, like you suggested.
#montgomery_spending_cleaned %>% 
# mutate(payee_cleaned = case_when(
#    str_detect(payee_cleaned, ", INC") ~ " INC",
#   str_detect(payee_cleaned, ", PC") ~ " PC",
#    str_detect(payee_cleaned, ", LLC") ~ " LLC",
#    str_detect(payee_cleaned, ", LLP") ~ " LLP",
#    str_detect(payee_cleaned, ", DPC") ~ " DPC",
#    TRUE ~ payee_cleaned)) %>% 
#  filter(str_detect(payee_cleaned, "INC"))

#omitting commas
montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(payee_cleaned = str_replace_all(payee_cleaned, ",", ""))

#creating a new column to distinguish between individual and group payees
montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(payee_type = case_when(payee_cleaned == "BANNISTER JOI" | 
                                  payee_cleaned == "DAMAS STANISLAW" | 
                                  payee_cleaned == "HAGGERTY JOHN" | 
                                  payee_cleaned == "HYMAN ANDREW J" | 
                                  payee_cleaned == "MDINGI EMMANUEL" | 
                                  payee_cleaned == "THOMPSON JOHN" | 
                                  payee_cleaned == "TSENG PAUL" | 
                                  payee_cleaned == "WARFIELD BERNARD T" | 
                                  payee_cleaned == "CHEONG AMANDA" | 
                                  payee_cleaned == "CLEARY JR VINCENT" | 
                                  payee_cleaned == "RODRIGUEZ KATHLEEN M" | 
                                  payee_cleaned == "BETANCES PAUL A" | 
                                  payee_cleaned == "DORSEY LATISA T" | 
                                  payee_cleaned == "GEMBERLING KATHERYN W" | 
                                  payee_cleaned == "NEYLON SHAWN" | 
                                  payee_cleaned == "NORMOYLE RICHARD M" | 
                                  payee_cleaned == "WILCZYNSKI SUZANNE S" | 
                                  payee_cleaned == "EY CRYSTAL" | 
                                  payee_cleaned == "GROSS, DANIEL E" | 
                                  payee_cleaned == "HONIG MEREDITH" | 
                                  payee_cleaned == "KRAMER ETHAN" | 
                                  payee_cleaned == "REIDER KELLY" ~ "individual",
                                TRUE ~ "group"))

#spot check
montgomery_spending_cleaned %>% 
  filter(str_detect(payee_cleaned, "NEYLON SHAWN"))

#changing NAs in agency_name column to show Montgomery County Public Schools
montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(agency_name = replace_na("MONTGOMERY COUNTY PUBLIC SCHOOLS"))

#I tried this before the above, but it messed up some of the payee names that contained the letters "NA".
#montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  #mutate(payee_cleaned = str_replace(payee_cleaned, "NA", "MONTGOMERY COUNTY PUBLIC SCHOOLS"))

#standardizing payees with "&" in the name
#Some companies seem not to use spaces around the "&" while others do. In an effort to make the dataframe more easily searchable, I decided to omit spaces around instances of "&" between two initials, not when "&" separates two complete words. Not sure if I made the right decision here, but I made a decision!
#In a similar vein, I omitted spaces between initials. I'm sure I missed some, but I wasn't sure how to find them other than reading through the whole dataframe.
montgomery_spending_cleaned %>% 
  filter(str_detect(payee_cleaned, "&"))

montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(payee_cleaned = case_when(
    str_detect(payee_cleaned, "B & H FOTO & ELECTRONICS CORP") ~ "B&H FOTO & ELECTRONICS CORP",
    str_detect(payee_cleaned, "T L GARDEN & ASSOCIATES INC") ~ "TL GARDEN & ASSOCIATES INC",
    str_detect(payee_cleaned, "YOTI N N & ASSOCIATES INC") ~ "YOTI NN & ASSOCIATES INC",
    str_detect(payee_cleaned, "D & F CONSTRUCTION CO INC") ~ "D&F CONSTRUCTION CO INC",
    str_detect(payee_cleaned, "W W NORTON & COMPANY INC") ~ "WW NORTON & COMPANY INC",
    str_detect(payee_cleaned, "WW NORTON & CO INC") ~ "WW NORTON & COMPANY INC",
    str_detect(payee_cleaned, "H & S BAKERY INC") ~ "H&S BAKERY INC",
    str_detect(payee_cleaned, "R & S AUTO & TRUCK SPRING WORKS INC") ~ "R&S AUTO & TRUCK SPRING WORKS INC",
    str_detect(payee_cleaned, "L & L MUSIC WIND SHOP INC") ~ "L&L MUSIC WIND SHOP INC",
    str_detect(payee_cleaned, "C N ROBINSON LIGHTING SUPPLY CO INC") ~ "CN ROBINSON LIGHTING SUPPLY CO INC",
    str_detect(payee_cleaned, "W W GRAINGER INC") ~ "WW GRAINGER INC",
    str_detect(payee_cleaned, "M T LANEY CO INC") ~ "MT LANEY CO INC",
    str_detect(payee_cleaned, "M R ENTERPRISES INC") ~ "MR ENTERPRISES INC",
    str_detect(payee_cleaned, "LAND OLAKES INC") ~ "LAND O LAKES INC",
    TRUE ~ payee_cleaned))

#getting rid of apostrophes
montgomery_spending_cleaned %>% 
  filter(str_detect(payee_cleaned, "'"))

montgomery_spending_cleaned <- montgomery_spending_cleaned %>% 
  mutate(payee_cleaned = str_replace_all(payee_cleaned, "'", ""))

#A concern I had is that some payees have more than one zip code listed. I suppose they could have moved, so I didn't mess with these.

```

```{r}
#writing the final version to csv
write_csv(montgomery_spending_cleaned, "~/Documents/GitHub/news_apps_spring_2022/final_montgomery_spending.csv")

```

```{r}
#Exploring the cleaned data
#I was surprised that there were so many individual payees. How many of them were affiliated with one of the "group" payees? For instance, Emmanuel Mdingi seems to be affiliated with the Rockville-based architectural firm DCI Architects.

montgomery_spending_cleaned %>% 
  group_by(fiscal_year) %>% 
  summarize(total = sum(amount)) %>% 
  arrange(desc(total))
 
 #Are we missing FY2019??

montgomery_spending_cleaned %>% 
  group_by(payee_cleaned) %>% 
  summarize(total = sum(amount)) %>% 
  arrange(desc(total))
  
#The payees that received the most money were construction firms and contractors, with the exception of the top payee, which was Banc of America Public Capital Corporation. I wonder if they manage MCPS pension fund investments? What did Montgomery Public Schools build or renovate during these years?
 
#MCPS paid more than $1 million to the Storm Water Management Facilities Repair Group Inc. What was being repaired? Is it normal for the school system to shoulder this cost?
   
#MCPS paid more than $33,000 to the Audobon Naturalist Society of the Central Atlantic States. I wonder what that was about.
--
# BOE spending update
# number of records per year - The data shows the least records for FY2018 (615), while 2020-2022 vary between 708 and 710 records. This seems pretty normal to me. This also confirms that we are missing 2019.
montgomery_spending_cleaned %>% 
  group_by(fiscal_year) %>% 
  summarize(count = n())

#I want to make sure I understand the data correctly. Is each record one instance of a payee receiving a payment of more than $25,000, or does each entry represent a payee's total received payments amounting to more than $25,000 in a year?

#To answer this question, I found the payees with the largest number of entries per year. It appears that it is possible for a payee to have multiple entries per year, but since these are only expenditures greater than $25,000, the numbers of payments per payee aren't large.
montgomery_spending_cleaned %>% 
  filter(fiscal_year == "2018") %>% 
  group_by(payee_cleaned) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

montgomery_spending_cleaned %>% 
  filter(fiscal_year == "2020") %>% 
  group_by(payee_cleaned) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

#Top payees per year
#Overall thoughts: Lots of construction. I'm still curious about what Banc of America Public Capital Corp is doing. American Truck & Bus is a consistent presence - probably for school bus sales and/or upkeep - as are IT services companies.

#2018: Construction companies dominate the top five, with the only exception being number 4, Banc of America Public Capital Corp (investing pension fund money?). The top five are Hess Construction and Engineering Services Inc ($51.6 million), Oak Contracting LLC ($38 million), Dustin Construction Inc ($35.3 million), Banc of America Public Capital Corp ($32.3 million), Henley Construction Co Inc ($19.2 million).
#The others include a company that sells IT software, one that sells buses, Pepco, etc.
montgomery_spending_cleaned %>% 
  filter(fiscal_year == "2018") %>% 
  group_by(payee_cleaned) %>% 
  summarize(total = sum(amount)) %>% 
  arrange(desc(total)) %>% 
  slice(1:10)

#2020: Still a lot of construction and Banc of America Public Capital Corp, but the construction companies aren't all the same: Keller Construction Management Inc ($66.6 million), Dustin Construction Inc ($53.6 million), Hess Construction and Engineering Services Inc ($36.7 million), Henley Construction Co Inc ($30.8 million). Fifth place is CDW LLC, the IT solutions company ($30.6 million). Banc of America Public Capital Corp again ($26.4 million). Keller Brothers Inc and Keller Construction Management Inc are part of the same company (https://kellerbrothers.com/about), but I figured maybe it's helpful to keep them disaggregated.
montgomery_spending_cleaned %>% 
  filter(fiscal_year == "2020") %>% 
  group_by(payee_cleaned) %>% 
  summarize(total = sum(amount)) %>% 
  arrange(desc(total)) %>% 
  slice(1:10)

#2021: Payments to the IT software company, CDW LLC, are up, to $53.5 million (from something like $18 million in FY2018 and $30 million in FY2020), in addition to Data Networks of America Inc, another IT services company. Otherwise, Keller Brothers Inc and Dustin Construction Inc still made the top ten. Maybe interesting that payments to American Truck & Bus didn't decrease in a year when school was mostly from home. Is it weird that it's the exact same number?
montgomery_spending_cleaned %>% 
  filter(fiscal_year == "2021") %>% 
  group_by(payee_cleaned) %>% 
  summarize(total = sum(amount)) %>% 
  arrange(desc(total)) %>% 
  slice(1:10)

#2022: Keller Brothers Inc, Hess Construction and Engineering Services, and Dustin Construction Inc still made the top ten. There's some variation from previous years, but nothing crazy.
montgomery_spending_cleaned %>% 
  filter(fiscal_year == "2022") %>% 
  group_by(payee_cleaned) %>% 
  summarize(total = sum(amount)) %>% 
  arrange(desc(total)) %>% 
  slice(1:10)

#Wanted to check for missing payment amounts - didn't see anything
montgomery_spending_cleaned %>% 
  filter(str_detect(amount, "NA"))
```

   

